### ISSUE TITLE
Users are too extensive

### ISSUE THREAD

**Issue by sjspielman** [wilkelab/wilkelab.github.io#1]
I graduated in  2016 ;)

**Comment by clauswilke** [comment]
you could submit a PR to fix it. :-)

**Comment by sjspielman** [comment]
You can do this for users? Did not know! I'll figure it out..

**Comment by clauswilke** [comment]
I thought you were commenting on something posted on the website. If you want me to remove your github access, you should say so explicitly, so I understand your request.

**Comment by sjspielman** [comment]
Apologies for the lack of clarity. At this stage, I recommend removing my github access for the wilke lab website.

**Comment by clauswilke** [comment]
Done.
